### ISSUE TITLE
Incomplete code in fooof_get_model

### ISSUE THREAD

**Issue by maartss** [fooof-tools/fooof_mat#13]
Hello,

It appears to be missing code in the fooof_get_model script.

Would we be able to have access to the complete script?

Many thanks.

**Comment by TomDonoghue** [comment]
Hey! I'm not sure what you mean? What code do you think is missing from `fooof_get_model.m`? Is something not working as expected?

**Comment by TomDonoghue** [comment]
Hey @maartss - just a ping on this. I'm not sure what you were referring to here. If you can expand on this a bit, I can try and help, otherwise I'll close this issue.

**Comment by maartss** [comment]
Apologies Tom, yes you can close this issue as the problem was elsewhere and could be solved.
Thanks!

**Comment by TomDonoghue** [comment]
Awesome great, glad to hear it! Thanks for trying it out, let us know if you have any other questions!
