### ISSUE TITLE
Matlab crashed when calling fooof functions

### ISSUE THREAD

**Issue by luop0812** [fooof-tools/fooof_mat#20]
OS: Red Hat 7.7
Matlab: 2019b
Python: 3.8, installed with conda
Sample: fooof_example_one_spectra.m
Error:

--------------------------------------------------------------------------------
       Segmentation violation detected at Tue Aug 04 10:38:27 2020 -0400
--------------------------------------------------------------------------------

I have 20G memory allocated for my job and the stack is set to unlimited. So I don't think it is a problem of memory or stack sizes. The stack trace is attached.
[matlab_crash_dump.17350-1.log](https://github.com/fooof-tools/fooof_mat/files/5023945/matlab_crash_dump.17350-1.log)

**Comment by TomDonoghue** [comment]
This appears to be some kind of issue with Matlab and/or it's Python wrapper. It's not something I can offer any help with unfortunately. You can explore the other issues and README info for stuff people have tried to get Matlab to work, or explore the Mat -> Py -> Mat approach, using FOOOF directly in Python in an otherwise Matlab workflow (https://github.com/fooof-tools/mat_py_mat)

**Comment by luop0812** [comment]
The problem was solved. It is caused by incompatibility between the Matlab blas library and the python virtual env bras library. Calling from Matlab, fooof will use the Matlab blas library and will crash. The solution is to set LD_PRRLOAD=/path/to/fooof_python_env/libblas.so, and fooof_mat works on Linux. 

https://www.mathworks.com/matlabcentral/answers/327193-calling-python-module-from-matlab-causes-segmentation-fault-in-h5py

**Comment by ludovicbellier** [comment]
Thanks for this solution, it just helped me!
From the link you shared, I even found a simpler solution than setting up an environment variable: simply run `py.sys.setdlopenflags(int32(10));` in MATLAB before calling fooof.m (or, inside fooof.m, before calling fm.fit on line 56, which was the specific line that made my MATLAB crash).
