### ISSUE TITLE
Make sure this stuff all works. 

### ISSUE THREAD

**Issue by TomDonoghue** [fooof-tools/fooof_mat#4]
Okay, so I checked everything was working on my computer as I went, but this stuff, in particular the Matlab wrapper, is not that well extensively tested.

 I also wrote out the README sorta from memory, so sanity checking the descriptions to get things set up would be great, especially with someone actually working through this stuff. 

Basically - anyone and everyone who can try this stuff out, and make sure it all works them would be great. Let me know if and what breaks.

**Comment by vpapadourakis** [comment]
Not sure where to put this but exist doesn't work this way. In fooof_check_settings.m
you should use ~isfield(settings,'max_n_peaks')  instead of ~exist('settings.max_n_peaks').

MATLAB R2017b here. 

Thanks for the wrapper btw

**Comment by TomDonoghue** [comment]
Hey @vpapadourakis 

Ahh, wow, yeah, you are totally right! My Matlab-ing is definitely rusty, and I completely messed that up (I feel like I copied that approach from somewhere, and I guess mis-understood it - didn't check it enough). 

Anyways - huge thanks for catching this and pointing it out! I have updated it now to use 'isfield'!
