### ISSUE TITLE
Plotting outputs Matlab wrapper

### ISSUE THREAD

**Issue by mgm248** [fooof-tools/fooof_mat#8]
Hello,

I was hoping to be able to save plots using the Matlab wrapper, but I am running into a problem. I was hoping, after running FOOOF with fm.fit, where fm is the FOOOF object, I could run fm.save_report(filename), or fm.report and generate a report without having to leave matlab. However, both of these commands led to this error: 

![matlab_error_8_28](https://user-images.githubusercontent.com/20707533/44748061-c8038100-aadc-11e8-9683-af551402bf01.jpg)

Any idea where this came from / suggestions? I checked and I do have Matplotlib installed. Any help is appreciated :)

**Comment by TomDonoghue** [comment]
As of right now - this wrapper is super minimal, and only really supports the basics of running the model and getting the results.

I would like to extend it a bit as soon as I can a chance (hopefully will take some time to work on it next week). Of the top of my head, I don't know if / how the reports / plotting / saving, etc will work - but I will try to get back to you soon!

**Comment by mgm248** [comment]
Ok, no problem -- thanks for the quick response!

**Comment by mgm248** [comment]
^ Just figured this out -- I was using log(), which is natural log in matlab, instead of log10().

**Comment by TomDonoghue** [comment]
Hey @mgm248 : sorry I didn't get back to this earlier - I was traveling back then. If you have some Matlab code to regenerate the model from FOOOF-results, and re-create a plot, would you mind sharing that code? It might something useful to add into this wrapper in general, so that everyone can do that same as you set up. I can help organize the code to merge into the repo here, if you'd like.

**Comment by TomDonoghue** [comment]
Also, @mgm248 : perhaps of interest, I just added support for getting the fooof model, and plotting it. 

I would still be curious for the code you used to regenerate the model!

**Comment by vpapadourakis** [comment]
I wrote a plot function at some point

https://github.com/vpapadourakis/fooof_mat/blob/master/matlab_wrapper_examples/plot_one_foof_results.m

It's been a while but it should work.
